import { readFile, rename, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { validateExpansionCatalog } from './catalog-schema.mjs'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..')
const DEFAULT_INPUT = path.join(REPO_ROOT, 'docs', 'superpowers', 'catalog', 'expansion', 'candidates.json')
const DEFAULT_OUTPUT = path.join(REPO_ROOT, 'docs', 'superpowers', 'catalog', 'expansion', 'CATALOG.md')

const WAVE_ORDER = ['browser-native', 'work', 'at-a-glance', 'broader', 'backlog']
const WAVE_LABEL = Object.freeze({
  'browser-native': 'Browser native',
  work: 'Work',
  'at-a-glance': 'At a glance',
  broader: 'Broader',
  backlog: 'Backlog',
})

function list(values) {
  return values.length > 0 ? values.join('; ') : 'None'
}

function yesNo(value) {
  return value ? 'Yes' : 'No'
}

function detail(candidate) {
  return `### ${candidate.label} (\`${candidate.id}\`)

- **User value:** ${candidate.userValue}
- **Glance question:** ${candidate.glanceQuestion}
- **Source:** [${candidate.source.provider}](${candidate.source.docsUrl}), \`${candidate.source.transport}\`
- **Authentication:** ${candidate.auth.mode}; direct MV3: ${yesNo(candidate.auth.directClientViable)}; ${candidate.auth.secretHandling}
- **Chrome permissions:** ${list(candidate.access.chromePermissions)}
- **Origins:** ${list(candidate.access.origins)}
- **User warnings:** ${list(candidate.access.userWarnings)}
- **Privacy sent:** ${list(candidate.privacy.sends)}
- **Privacy received:** ${list(candidate.privacy.receives)}
- **Privacy stored:** ${list(candidate.privacy.stores)}
- **Backup:** ${candidate.privacy.backup}
- **Redaction:** ${candidate.privacy.redaction}
- **Freshness:** ${candidate.cache.freshness}
- **Stale behavior:** ${candidate.cache.staleBehavior}
- **Refresh:** ${candidate.cache.refresh}
- **Failure:** ${candidate.cache.failure}
- **Setup:** ${list(candidate.settings.setup)}
- **Controls:** ${list(candidate.settings.controls)}
- **Validation:** ${list(candidate.settings.validation)}
- **Compact:** ${candidate.presentation.compact}
- **Standard:** ${candidate.presentation.standard}
- **Full:** ${candidate.presentation.full}
- **Docked:** ${candidate.presentation.docked}
- **Interaction:** ${candidate.presentation.interaction}
- **Empty:** ${candidate.presentation.empty}
- **Loading:** ${candidate.presentation.loading}
- **Stale:** ${candidate.presentation.stale}
- **Error:** ${candidate.presentation.error}
- **Maintenance:** ${candidate.maintenance.risk}; ${list(candidate.maintenance.drivers)}
- **Rationale:** ${candidate.decision.rationale}
- **Blockers:** ${list(candidate.decision.blockers)}
`
}

export function renderExpansionCatalog(catalog) {
  const sections = []
  for (const wave of WAVE_ORDER) {
    const candidates = catalog.candidates.filter((candidate) => candidate.wave === wave)
    if (candidates.length === 0) continue
    const rows = candidates.map((candidate) =>
      `| ${candidate.priority} | ${candidate.label} | ${candidate.status} | ${candidate.kind} | ${candidate.auth.mode} | ${yesNo(candidate.auth.directClientViable)} | ${candidate.source.termsRisk} | ${candidate.maintenance.risk} |`,
    )
    sections.push(`## ${WAVE_LABEL[wave]}

| Priority | Candidate | Status | Kind | Auth | Direct MV3 | Terms | Maintenance |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

${candidates.map(detail).join('\n')}`)
  }

  return `# Aurora Expansion Candidate Catalog

> Generated from \`candidates.json\`. Do not edit this file directly.

**Catalog version:** ${catalog.catalogVersion}  
**Research verified:** ${catalog.verifiedOn}  
**Candidates:** ${catalog.candidates.length}

## Status legend

- \`approved-wave\`: sequenced by the owner-approved roadmap; its packet still owns permission and privacy acceptance.
- \`researched\`: viable enough to compare but not scheduled.
- \`deferred\`: useful, but cost or scope places it later.
- \`absorbed\`: its value belongs inside an existing Aurora identity.
- \`blocked\`: the current provider, auth, policy, or architecture is not shippable.

${sections.join('\n')}`
}

function parseArgs(args) {
  const parsed = { input: DEFAULT_INPUT, output: DEFAULT_OUTPUT, check: false }
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index]
    if (argument === '--check') {
      parsed.check = true
      continue
    }
    const [flag, inline] = argument.split('=', 2)
    if (flag !== '--input' && flag !== '--output') throw new Error(`unknown argument: ${argument}`)
    const value = inline ?? args[++index]
    if (!value) throw new Error(`${flag} requires a path`)
    parsed[flag.slice(2)] = path.resolve(value)
  }
  return parsed
}

async function readValidatedCatalog(input) {
  let value
  try {
    value = JSON.parse(await readFile(input, 'utf8'))
  } catch (error) {
    return { ok: false, errors: [`catalog: ${error instanceof Error ? error.message : String(error)}`] }
  }
  return validateExpansionCatalog(value)
}

export async function runCatalogCli(args, report = () => {}) {
  let options
  try {
    options = parseArgs(args)
  } catch (error) {
    report(error instanceof Error ? error.message : String(error))
    return 1
  }

  const result = await readValidatedCatalog(options.input)
  if (!result.ok) {
    result.errors.forEach(report)
    return 1
  }
  const markdown = renderExpansionCatalog(result.catalog)

  if (options.check) {
    try {
      return await readFile(options.output, 'utf8') === markdown ? 0 : 1
    } catch {
      return 1
    }
  }

  const temporary = `${options.output}.tmp-${process.pid}-${Date.now()}`
  try {
    await writeFile(temporary, markdown, { encoding: 'utf8', flag: 'wx' })
    await rename(temporary, options.output)
  } catch (error) {
    await unlink(temporary).catch(() => {})
    report(error instanceof Error ? error.message : String(error))
    return 1
  }
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const code = await runCatalogCli(process.argv.slice(2), (message) => process.stderr.write(`${message}\n`))
  process.exitCode = code
}
