import assert from 'node:assert/strict'
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'

import { renderExpansionCatalog, runCatalogCli } from './render-catalog.mjs'

function candidate(id = 'readingList', label = 'Reading List') {
  return {
    id,
    label,
    kind: 'browser-native',
    status: 'approved-wave',
    wave: 'browser-native',
    priority: 1,
    userValue: 'Resume saved reading without opening another app.',
    glanceQuestion: 'What did I save to read next?',
    source: {
      provider: 'Google Chrome',
      docsUrl: 'https://developer.chrome.com/docs/extensions/reference/api/readingList',
      transport: 'chrome.readingList',
      termsRisk: 'low',
    },
    auth: {
      mode: 'browser-permission',
      directClientViable: true,
      secretHandling: 'No provider secret.',
    },
    access: {
      chromePermissions: ['readingList'],
      origins: [],
      userWarnings: ['Read and change entries in your reading list.'],
    },
    privacy: {
      sends: [],
      receives: ['Saved page titles, URLs, and read state from Chrome.'],
      stores: ['Selected display preferences only.'],
      backup: 'Display preferences only.',
      redaction: 'No credential redaction required.',
    },
    cache: {
      freshness: 'Read from Chrome on mount and change events.',
      staleBehavior: 'Keep the last in-memory list until the next Chrome event.',
      refresh: 'Refresh on reading-list change and visibility.',
      failure: 'Show a local API error without deleting saved data.',
    },
    settings: {
      setup: [],
      controls: ['Unread only', 'Maximum items'],
      validation: ['Maximum items is an integer from 1 through 10.'],
    },
    presentation: {
      compact: 'Unread count and next title.',
      standard: 'Next saved pages with age.',
      full: 'Readable saved-page queue with read state.',
      docked: 'Unread count and next title.',
      interaction: 'Open a saved page; details manage read state.',
      empty: 'Nothing saved to read.',
      loading: 'Reading saved pages.',
      stale: 'Keep the last Chrome-owned list with a stale label.',
      error: 'Reading List is unavailable; retry.',
    },
    maintenance: {
      risk: 'low',
      drivers: ['Chrome 120 minimum for the API.'],
    },
    decision: {
      rationale: 'High repeat value with no external account.',
      blockers: ['Accept the optional readingList permission warning.'],
    },
  }
}

function validCatalog() {
  return {
    catalogVersion: 1,
    verifiedOn: '2026-08-22',
    candidates: Array.from({ length: 36 }, (_, index) => candidate(`candidate${index + 1}`, `Candidate ${index + 1}`)),
  }
}

test('renders every candidate field into deterministic Markdown', () => {
  const markdown = renderExpansionCatalog({
    catalogVersion: 1,
    verifiedOn: '2026-08-22',
    candidates: [candidate()],
  })

  assert.equal(markdown, `# Aurora Expansion Candidate Catalog

> Generated from \`candidates.json\`. Do not edit this file directly.

**Catalog version:** 1  
**Research verified:** 2026-08-22  
**Candidates:** 1

## Status legend

- \`approved-wave\`: sequenced by the owner-approved roadmap; its packet still owns permission and privacy acceptance.
- \`researched\`: viable enough to compare but not scheduled.
- \`deferred\`: useful, but cost or scope places it later.
- \`absorbed\`: its value belongs inside an existing Aurora identity.
- \`blocked\`: the current provider, auth, policy, or architecture is not shippable.

## Browser native

| Priority | Candidate | Status | Kind | Auth | Direct MV3 | Terms | Maintenance |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | Reading List | approved-wave | browser-native | browser-permission | Yes | low | low |

### Reading List (\`readingList\`)

- **User value:** Resume saved reading without opening another app.
- **Glance question:** What did I save to read next?
- **Source:** [Google Chrome](https://developer.chrome.com/docs/extensions/reference/api/readingList), \`chrome.readingList\`
- **Authentication:** browser-permission; direct MV3: Yes; No provider secret.
- **Chrome permissions:** readingList
- **Origins:** None
- **User warnings:** Read and change entries in your reading list.
- **Privacy sent:** None
- **Privacy received:** Saved page titles, URLs, and read state from Chrome.
- **Privacy stored:** Selected display preferences only.
- **Backup:** Display preferences only.
- **Redaction:** No credential redaction required.
- **Freshness:** Read from Chrome on mount and change events.
- **Stale behavior:** Keep the last in-memory list until the next Chrome event.
- **Refresh:** Refresh on reading-list change and visibility.
- **Failure:** Show a local API error without deleting saved data.
- **Setup:** None
- **Controls:** Unread only; Maximum items
- **Validation:** Maximum items is an integer from 1 through 10.
- **Compact:** Unread count and next title.
- **Standard:** Next saved pages with age.
- **Full:** Readable saved-page queue with read state.
- **Docked:** Unread count and next title.
- **Interaction:** Open a saved page; details manage read state.
- **Empty:** Nothing saved to read.
- **Loading:** Reading saved pages.
- **Stale:** Keep the last Chrome-owned list with a stale label.
- **Error:** Reading List is unavailable; retry.
- **Maintenance:** low; Chrome 120 minimum for the API.
- **Rationale:** High repeat value with no external account.
- **Blockers:** Accept the optional readingList permission warning.
`)
})

test('check mode reports stale Markdown without changing its bytes', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'aurora-expansion-catalog-'))
  t.after(() => rm(root, { recursive: true, force: true }))
  const input = path.join(root, 'candidates.json')
  const output = path.join(root, 'CATALOG.md')
  await writeFile(input, `${JSON.stringify(validCatalog(), null, 2)}\n`, 'utf8')
  await writeFile(output, 'stale bytes\n', 'utf8')

  const code = await runCatalogCli(['--input', input, '--output', output, '--check'])

  assert.equal(code, 1)
  assert.equal(await readFile(output, 'utf8'), 'stale bytes\n')
  assert.deepEqual((await readdir(root)).sort(), ['CATALOG.md', 'candidates.json'])
})

test('normal mode atomically writes validated Markdown', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'aurora-expansion-catalog-'))
  t.after(() => rm(root, { recursive: true, force: true }))
  const input = path.join(root, 'candidates.json')
  const output = path.join(root, 'CATALOG.md')
  const catalog = validCatalog()
  await writeFile(input, `${JSON.stringify(catalog, null, 2)}\n`, 'utf8')

  const code = await runCatalogCli(['--input', input, '--output', output])

  assert.equal(code, 0)
  assert.equal(await readFile(output, 'utf8'), renderExpansionCatalog(catalog))
  assert.deepEqual((await readdir(root)).sort(), ['CATALOG.md', 'candidates.json'])
})

test('invalid input leaves no output or temporary file', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'aurora-expansion-catalog-'))
  t.after(() => rm(root, { recursive: true, force: true }))
  const input = path.join(root, 'candidates.json')
  const output = path.join(root, 'CATALOG.md')
  await writeFile(input, '{"catalogVersion":1,"verifiedOn":"2026-08-22","candidates":[]}', 'utf8')

  const code = await runCatalogCli(['--input', input, '--output', output])

  assert.equal(code, 1)
  assert.deepEqual(await readdir(root), ['candidates.json'])
})
